# Generated by Django 4.2.13 on 2024-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
