# Generated by Django 4.2.13 on 2024-06-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_problem_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='big_hint',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='remark_for_big_hint',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='remark_for_small_hint',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='small_hint',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
